language: node_js
sudo: false
node_js:
  - "10"
install:
  - npm install
script:
  - npm run build && npm run lint && npm test
deploy:
  provider: npm
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true

